modLoader="javafml" #mandatory

loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="amrpc" #mandatory

version="1.0.2" #mandatory

displayName="Amitoj's Minecraft RPC" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://shrt.amitoj.net/minecraftRPC" #optional

logoFile="logo.png" #optional

credits="Thanks to Amitoj Singh" #optional

authors="Amitoj Singh" #optional

description='''

A Discord RPC mod for Minecraft (Forge)

'''
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
